name 'gehel-dashing'
version '1.0.0'

author 'Guillaume Lederrey'
license 'Apache2'
project_page ''
source 'https://github.com/gehel/puppet-dashing'
summary 'Puppet module for dashing'
description 'This module installs and manages dashing. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
dependency 'example42/firewall', '>=2.0.0'
dependency 'example42/monitor', '>=2.0.0'
dependency 'netmanagers/nodejs', '>=0.1.1'
